maxatome/go-testdeep

cmp_funcs.go
cmp_funcs_bool.go
t.go
t_struct.go
tools/gen_funcs.pl

Add missing t.Helper() calls

---

check_test.go
td_all_test.go
td_any_test.go
td_array.go
td_array_each_test.go
td_array_test.go
td_bag_test.go
td_between.go
td_between_test.go
td_code_test.go
td_ignore_test.go
td_isa.go
td_isa_test.go
td_len_cap_test.go
td_map.go
td_map_each_test.go
td_map_test.go
td_nil_test.go
td_none_test.go
td_ptr_test.go
td_re_test.go
td_set_test.go
td_shallow_test.go
td_string_test.go
td_struct.go
td_struct_test.go
td_trunc_time.go
td_trunc_time_test.go
td_zero_test.go
types.go

Add TypeOf method to TestDeep interface

---

cmp_funcs_test.go
example_test.go
t_test.go
td_array.go
td_array_test.go
td_map.go
td_map_test.go
td_struct.go
td_struct_test.go

No panic when typed nil used in model of Array, Map, Slice & Struct

---

README.md
cmp_funcs.go
cmp_funcs_test.go
example_test.go
t.go
t_struct.go
t_test.go
td_code.go
td_len_cap.go
td_ptr.go
td_smuggle.go
td_smuggle_test.go
td_smuggler_base.go
td_struct_test.go
testdeep.go
types.go

Add Smuggle operator

---

README.md
cmp_funcs_misc.go
cmp_funcs_misc_test.go
context.go
t_struct.go
t_struct_test.go

Add CmpPanic & CmpNoPanic functions + same T methods

---

go.mod
testdeep.go

Switch to vgo

---

README.md
cmp_funcs.go
cmp_funcs_test.go
example_test.go
t.go
t_test.go
td_nan.go
td_nan_test.go

Add NaN and NotNaN operators (+ CmpNaN/NotNaN & T.CmpNaN/NotNaN)

---

cmp_funcs_test.go
example_test.go
t_test.go

Add ContainsKey examples

---

td_contains_key.go
td_contains_key_test.go

ContainsKey error reworked

---

go.mod
go.sum

Update go.mod + go.sum

---

td_all.go
td_any.go
td_map.go
td_none.go
td_re.go

It seems go-1.12 will inline more aggressively

---

.travis.yml
cmp_funcs.go
doc/FAQ.md
equal_test.go
internal/dark/copy_test.go
t.go
td_code_test.go
td_smuggle_test.go
tools/gen_funcs.pl
types.go

Add some items in FAQ

---

td_all.go
td_all_test.go
td_isa_test.go

It tries to do its best to return a valid and unique type.

Implement All() TypeBehind() method

---

internal/ctxerr/error_private_test.go

Add unit tests

---

cmp_deeply_test.go
equal_examples_test.go
equal_test.go
internal/ctxerr/error.go
internal/location/location.go
internal/test/check.go
private_test.go
td_all.go
td_any.go
td_map.go
td_none.go
td_re.go
types.go
types_test.go

Rework set location

---

config.go
internal/ctxerr/context.go
internal/visited/visited.go
internal/visited/visited_test.go

Move ctxerr.Visited in its own package

---

README.md
cmp_funcs.go
example_cmp_test.go
example_t_test.go
example_test.go
t.go
t_struct_test.go
td_struct.go
td_struct_test.go
tools/docs_src/content/operators/SStruct.md
tools/docs_src/content/operators/_index.md
tools/docs_src/content/operators/matrix.md
tools/gen_funcs.pl

Same as Struct operator except that omitted fields are checked against
the zero value of their type.

Add SStruct operator (a.k.a. strict-Struct)

---

helpers/tdhttp/http.go
helpers/tdhttp/http_test.go
helpers/tdhttp/request_test.go
helpers/tdhttp/test_api.go
internal/test/types.go
td/cmp_deeply_test.go
td/config.go
td/t_anchor.go
td/t_anchor_go114.go
td/t_anchor_other.go
td/t_anchor_test.go
td/t_struct.go
td/t_struct_test.go
td/types.go
td_compat.go

td.TestingFT → testing.TB

---

internal/visited/visited.go
internal/visited/visited_test.go
td/equal_test.go

Thanks to @stewi1014 for the issue and the test case.
Closes #101

fix(visited): some data recursion cases was not correctly handled

---

td/equal.go
td/td_any.go
td/td_any_test.go
td/td_bag_test.go
td/td_code.go
td/td_code_test.go
td/td_contains.go
td/td_contains_key.go
td/td_contains_key_test.go
td/td_contains_test.go
td/td_none.go
td/td_none_test.go
td/td_set_base.go
td/td_set_test.go

- Any
- Code
- Contains
- None
- NotAny
- Set
- SubSetOf
- SuperSetOf
- Bag
- SubBagOf
- SuperBagOf

fix(Lax): BeLax flag was not taken into account for some operators

---

helpers/tdhttp/http_test.go
helpers/tdhttp/internal/response.go
helpers/tdhttp/internal/response_test.go
helpers/tdhttp/test_api.go
helpers/tdhttp/test_api_test.go

feat(tdhttp): add With, T, Run, OrDumpResponse and AutoDumpResponse

---

internal/test/check.go
td/example_cmp_test.go
td/example_t_test.go
td/example_test.go
td/t_hooks.go
td/td_ignore.go
td/td_struct.go
td/td_struct_private_test.go
td/td_struct_test.go

feat: Struct & SStruct now understand shell patterns & regexps

---

helpers/tdhttp/multipart.go
helpers/tdhttp/multipart_test.go
helpers/tdhttp/request.go
helpers/tdhttp/request_test.go
helpers/tdhttp/test_api.go
helpers/tdhttp/test_api_test.go

and so compliant with RFC 2388

feat(tdhttp): introduce multipart requests as defined in RFC 2046

---

td/cmp_funcs.go
td/example_cmp_test.go
td/example_t_test.go
td/example_test.go
td/t.go
td/td_struct.go
td/td_struct_private_test.go
tools/gen_funcs.pl

If multiple, all maps are merged from left to right.

feat(Struct,SStruct): expectedFields now optional or multiple

---

helpers/tdsuite/suite.go
helpers/tdsuite/suite_test.go

Given the 5 hooks:
- Setup
- PreTest
- PostTest
- BetweenTests
- Destroy
raise an error when a method is defined on a tdsuite with one of these
names but without matching the proper interface.

fix(tdsuite): detect wrongly defined hooks

---

td/example_cmp_test.go
td/example_t_test.go
td/example_test.go

This is a small PR to fix a spelling error.
Thanks

Correct spelling least

---

td/cmp_funcs_misc.go
td/cmp_funcs_misc_test.go
td/t_struct.go

See https://pkg.go.dev/runtime#PanicNilError for details.

docs: clarify panic(nil) case since go 1.21 introduced a change

---

helpers/tdsuite/suite_test.go

fix(tdsuite): verbose tests raised an error

---

helpers/tdutil/sort_values_121_test.go
internal/sort/sort.go
internal/sort/sort_121_test.go
internal/sort/sort_test.go

vals := []reflect.Value{…}
slices.SortFunc(vals, tdutil.CmpValuesFunc())

feat(tdutil): add new function CmpValuesFunc for slices.SortFunc
