.travis.yml
The `go_import_path` option of Travis-CI (see [doc](https://docs.travis-ci.com/user/languages/go/)) allows to tell Travis-CI the path where the code should be cloned in $GOPATH.
This allows external contributors to use Travis-CI on their fork without incorrectly running the testsuite with the original import path instead of their modified code.
=> Travis-CI: add go_import_path

README.md, cmp_deeply.go, cmp_deeply_test.go, cmp_funcs_misc.go, context.go, context_test.go, t_struct.go, t_struct_test.go, types.go, types_test.go
If set to true (via DefaultContextConfig.FailureIsFatal or using
T.FailureIsFatal), Fatal() method is called instead of Error() to
report tests failures.
=> Introducing FailureIsFatal feature

cmp_funcs_test.go, example_test.go, t_test.go, td_smuggle.go, td_smuggle_test.go, types.go
=> Smuggle operator more lax + func can return error

cmp_funcs_test.go, example_test.go, t_test.go, td_shallow.go, td_shallow_test.go
Add clarifications for string/slice cases.
=> Shallow now handles strings as well

README.md, check_test.go, cmp_funcs_test.go, equal.go, example_test.go, t_test.go, td_array_each_test.go, td_array_test.go, td_contains_key_test.go, td_map_each_test.go, td_shallow_test.go, td_smuggle.go, td_smuggle_test.go, td_struct_test.go, td_trunc_time_test.go
Add Testdeep operators vs go types table in README.
=> Dereference interfaces before calling Testdeep operators

td_all.go, td_any.go, td_any_test.go, td_list.go
=> Implement Any() TypeBehind() method (shared with All())

config.go, equal.go, internal/ctxerr/context.go, internal/ctxerr/visited.go, internal/ctxerr/visited_test.go
so deepValueEqual() is now shorter/less complex
=> ctxerr.Context.Visited has now its own type

helpers/tdhttp/request.go, helpers/tdhttp/request_test.go
```
strHeaders := []string{
"X-Length", "666",
"X-Foo", "bar",
}
req := NewRequest("POST", "/pdf", body, td.Flatten(strHeaders))
```
=> feat(tdhttp): NewRequest() headers can be flattened with td.Flatten()

internal/trace/trace.go, internal/trace/trace_test.go, td/cmp_deeply.go, td/cmp_deeply_test.go
- (*td.T).Run() and (*td.T).RunAssertRequire()
- (*tdhttp.TestAPI).Run()
- tdsuite package
=> fix(trace): ignore internal go-testdeep calls in error traces

internal/trace/stack.go, internal/trace/stack_test.go, internal/trace/trace.go, internal/trace/trace_test.go, td/cmp_deeply.go, td/cmp_deeply_test.go, tools/gen_funcs.pl
- testing.Cleanup()
- (*td.T).Run() and (*td.T).RunAssertRequire()
- (*tdhttp.TestAPI).Run()
- tdsuite package
=> fix(trace): ignore internal testing/go-testdeep calls in error traces

helpers/tdhttp/request.go, helpers/tdhttp/request_test.go, internal/types/types.go, internal/types/types_private_test.go, internal/types/types_test.go, td/td_json.go, td/td_json_test.go, td/types.go
for safety purposes, the json.Marshal()ling is now forbidden, but an
explicit error message is returned to the user.
=> fix(JSON): nested operators in JSON params are not json.Marshal()led

helpers/tdsuite/suite.go, helpers/tdsuite/suite_go114_test.go, helpers/tdsuite/suite_test.go
for TestXxx(assert, require *td.T) methods.
=> fix(tdsuite): Cleanup() wrongly called in PreTest/PostTest hooks

td/cmp_deeply.go
I'm capturing the output of "go test" (and hence go-testdeep) and prepending a string to the output. The yellow color of the test-name line leaks to the prefix of the next line.
Before this PR (see the third line):
```
⚫️ [prefix with default color] --- FAIL: TestParse (0.00s)
⚫️ [prefix with default color]    some_test.go:16: Failed test
🟡 [prefix with YELLOW color]          DATA: should NOT be an error
⚫️ [prefix with default color]                      got: (*errors.errorString)(0xc00010a780)(not implemented)
⚫️ [prefix with default color]                 expected: nil
...
```
After this PR:
```
⚫️ [prefix with default color] --- FAIL: TestParse (0.00s)
⚫️ [prefix with default color]      some_test.go:16: Failed test
⚫️ [prefix with default color]         DATA: should NOT be an error …
```
=> reset test name color before newline

internal/test/types.go, td/t_struct.go, td/t_struct_test.go
Add a Parallel() method to `*td.T` that calls `Parallel()` on the
underlying `testing.TB` if it supports the method. This will have no
effect on `*testing.B` or custom wrappers that do not support
`Parallel()`.
Per #149, this implements this as a method rather than a top-level
`td.Parallel(t)` function because this is closer to what existing usage
of `*testing.T` looks like.
Resolves #149
=> feat: add (*td.T).Parallel() method

helpers/nocolor/nocolor.go, helpers/nocolor/nocolor_test.go
to easily disable coloring output of failure reports, typically useful in golang playground.
=> feat: introduce nocolor helper

internal/ctxerr/context.go, internal/hooks/hooks.go, internal/hooks/hooks_test.go, td/config.go, td/equal.go, td/equal_test.go, td/t_struct.go, td/t_struct_test.go, td/td_struct.go, td/td_struct_test.go
IgnoreUnexported & UseEqual can now be scoped to some types.
=> feat: add IgnoreUnexported feature and rework UseEqual

helpers/tdhttp/doc.go, helpers/tdhttp/http.go, helpers/tdhttp/http_test.go, helpers/tdhttp/test_api.go
```bash
julien@julien-VirtualBox:~/git/go-testdeep$ go test ./... -cover
ok      github.com/maxatome/go-testdeep 0.038s  coverage: [no statements]
ok      github.com/maxatome/go-testdeep/helpers/nocolor 0.047s  coverage: 100.0% of statements
ok      github.com/maxatome/go-testdeep/helpers/tdhttp  0.075s  coverage: 99.4% of statements
ok      github.com/maxatome/go-testdeep/helpers/tdhttp/internal 0.017s  coverage: 100.0% of statements
ok      github.com/maxatome/go-testdeep/helpers/tdsuite 0.019s  coverage: 100.0% of statements
ok      github.com/maxatome/go-testdeep/helpers/tdutil  0.004s  coverage: 99.4% of statements
ok      github.com/maxatome/go-testdeep/internal/anchors        0.022s  coverage: 100.0% of statements
ok      github.com/maxatome/go-testdeep/internal/color  0.011s …
```
=> feat(tdhttp): add CmpCookies

td/td_json_test.go, td/td_len_cap.go, td/td_len_cap_test.go
because JSON uses float64 and Len/Cap expected int.
Len and Cap now accept any number type, not only int as before.
=> fix(Len/Cap): Len & Cap could not be used in JSON

td/td_json.go, td/td_json_test.go
=> fix(JSON): named placeholder values were not JSON {,un}marshalled

td/td_catch.go, td/td_catch_test.go
when type behind operator is not known.
=> fix(Catch): TypeBehind can fall back on target dereferenced type

td/example_cmp_test.go, td/example_t_test.go, td/example_test.go, td/td_json.go, td/td_json_pointer.go, td/td_json_test.go, td/td_smuggler_base.go, td/types_test.go, tools/gen_funcs.pl
JSON, SubJSONOf & SuperJSONOf adopt the same behavior as JSONPointer
for their placeholders. Got value is JSON marshalled then unmarshalled
in a new value matching the placeholder type.
=> feat(JSON): rework placeholders handling

internal/json/lex.go, internal/json/parser_go113_test.go, internal/json/parser_test.go, td/td_json.go
The following numbers are now accepted by JSON, SuperJSONOf and
SubJSONOf operators:
```
+42          → 42
4_2          → 42
0b101010     → 42
0b10_1010    → 42
0600         → 384
0_600        → 384
0o600        → 384
0O600        → 384 // second character is capital letter 'O'
0xBadFace    → 195951310
0x_Bad_Face  → 195951310
.25          → 0.25
1_5.         → 15.0
0.15e+0_2    → 15.0
0x1p-2       → 0.25
0x2.p10      → 2048.0
0x1.Fp+0     → 1.9375
0X.8p-0      → 0.5
0X_1FFFP-16  → 0.1249847412109375
```
=> feat(JSON): accept int_lit & float_lit numbers as defined in go spec

td/td_struct.go, td/td_struct_test.go
```go
td.Cmp(t, got, td.Struct(
Person{
Name:     "John Doe",
Age:      23,
Children: 4,
},
td.StructFields{
"> Age":     td.Between(40, 45),
">Children": 0, // spaces after ">" are optional
}),
)
```
=> feat: Struct & SStruct can override model fields in expectedFields

.github/workflows/ci.yml, helpers/tdsuite/suite_go114_test.go, helpers/tdsuite/suite_test.go, internal/anchors/anchor_test.go, internal/anchors/types_test.go, internal/util/string_test.go, td/example_test.go, td/td_isa_test.go, td/td_json.go, td/td_struct_test.go, td/td_trunc_time_test.go
Format the code using gofumpt. Cannot enable it as a linter as it
seems it detects old octal notation as not `gofumpt`-ed.
=> ci: add asciicheck & durationcheck linters

internal/ctxerr/context.go, internal/test/types.go, td/check_test.go, td/cmp_deeply.go, td/cmp_deeply_test.go, td/cmp_funcs.go, td/cmp_funcs_misc.go, td/config.go, td/config_test.go, td/equal.go, td/example_cmp_test.go, td/example_t_test.go, td/example_test.go, td/t_struct.go, td/td_code.go, td/td_code_test.go, td/types.go, td/utils_test.go, tools/gen_funcs.pl
Using two new kinds of function:
- `func(t *td.T, arg)`
- `func(assert, require *td.T, arg)`
this way the usage of `*td.T` methods is secure. Note that these
functions do not return anything.
At the same time, using a `*td.T` instance as `Cmp*` first parameter
allows to inherit its configuration.
```
td.Cmp(td.Require(t), got, 42)
```
is the same as:
```
td.Require(t).Cmp(got, 42)
```
=> feat(Code): Code can now officially delegate its comparison

helpers/tdhttp/internal/response_test.go
7f char is no longer escaped as \u007f in strings but \x7f.
=> test: fix test related to go1.19 change

internal/color/color.go, internal/color/color_test.go, internal/ctxerr/error.go, internal/ctxerr/summary.go, internal/ctxerr/summary_test.go, internal/json/lex.go, internal/util/string.go, internal/util/string_test.go, td/cmp_deeply.go, td/td_list.go, td/td_set_base.go
=> feat: replacing bytes.Buffer instances used only to generate strings with strings.Builder. 

internal/ctxerr/context.go, td/config.go, td/config_test.go, td/equal.go, td/equal_test.go, td/t_struct.go, td/t_struct_test.go
TestDeepInGotOK allows to accept TestDeep operator in got Cmp* parameter. By default it is forbidden and a panic occurs, because most of the time it is a mistake to compare (expected, got) instead of official (got, expected).
=> feat: add TestDeepInGotOK allowing to test td.TestDeep operators

internal/color/color.go, internal/ctxerr/error.go, internal/ctxerr/error_test.go, internal/ctxerr/summary.go, internal/ctxerr/summary_test.go, internal/util/string.go, internal/util/string_test.go, td/cmp_deeply.go
It is the same as `(*ctxerr.Error).Error`, but the string it returns does not contain any ANSI color escape sequences.
=> feat(internal): add (*ctxerr.Error).ErrorWithoutColors method

td/t_anchor_119.go, td/t_anchor_119_test.go, td/t_anchor_test.go
```
td.Anchor[string](t, td.HasPrefix("Pipo"))
```
vs
```
t.Anchor(td.HasPrefix("Pipo"), "").(string)
```
=> feat: add generic functions td.Anchor and td.A, another way to anchor

.github/workflows/ci.yml
The error message is:
GOPROXY list is not the empty string, but contains no entries
=> test: fix empty GOPROXY when testing with tip

td/check_test.go, td/equal.go, td/td_json.go, td/td_json_test.go, td/td_map.go, td/types.go
In error reports, the origin operator was sometimes missing and sometimes wrong when using JSON, SubJSONOf and SuperJSONOf operators, as in:
[under operator tdJSONUnmarshaler.resolveOp.func1 at lex.go:156]
Now the location of internal operators, as the ones used by JSON operators, cannot appear in error reports anymore and so do not mask the location of user visible operators.
=> fix(JSON): errors with wrong origin operator

.github/workflows/ci.yml, helpers/tdsuite/suite.go, internal/ctxerr/context.go, internal/ctxerr/context_test.go, internal/ctxerr/path.go, internal/json/lex.go, td/t_struct.go, td/td_struct.go
Except for stupid report about "unused-parameter".
=> refactor: make golangci-lint v1.52.2 happy

td/example_cmp_test.go, td/example_t_test.go, td/example_test.go, td/td_keys_values.go, td/td_shallow.go, td/td_struct.go, td/td_struct_lazy.go, td/td_struct_lazy_test.go, td/td_struct_test.go
model of Struct/SStruct can be nil. In this case, it is dynamically deduced from got during each match.
=> feat(Struct): introduce lazy-Struct & lazy-SStruct

internal/ctxerr/context.go, internal/ctxerr/context_test.go, td/td_json.go, td/td_json_test.go
Thanks to @mxpetit for the report.
=> Fix json panic

helpers/tdhttp/request.go, helpers/tdhttp/request_test.go, helpers/tdhttp/test_api.go, helpers/tdhttp/test_api_test.go
=> Add tdhttp.TestAPI's DefaultRequestParams & AddDefaultRequestParams

helpers/tdhttp/test_api.go, helpers/tdhttp/test_api_test.go
A testAPI can now be cloned without using the With statement.
=> feat(tdhttp): add testAPI.Clone feature

helpers/tdhttp/request.go, helpers/tdhttp/request_test.go
Accepted target can contain scheme://host:port prefix. If it is the case host:port is used to set Request.Host. If not and the header Host is present, it is used to set Request.Host.
=> feat(tdhttp): request creation methods/functions init Host field

internal/util/string.go, internal/util/string_test.go, internal/util/utils.go, internal/util/utils_test.go, td/equal.go, td/t_hooks.go, td/t_hooks_test.go, td/td_array.go, td/td_array_test.go, td/td_map.go, td/td_map_test.go, td/td_struct.go, td/td_struct_lazy_test.go, td/td_struct_test.go
=> Delay type checks

README.md, internal/ctxerr/summary.go, internal/dark/copy_test.go, internal/dark/interface_test.go, td/check_test.go, td/cmp_funcs.go, td/example_cmp_test.go, td/example_t_test.go, td/example_test.go, td/t.go, td/td_json.go, td/td_smuggle.go, td/td_smuggle_private_test.go, td/td_smuggle_test.go, td/td_sort.go, td/td_sort_private_test.go, td/td_sort_test.go, tools/gen_funcs.pl
=> Add Sort & Sorted operators

td/example_cmp_test.go, td/example_t_test.go, td/example_test.go, td/flatten.go, td/flatten_test.go, td/td_re.go
Allowing to use td.Re as function for example:
ok = td.Cmp(t,
strings.Split(got, "\n"),
td.List(td.Flatten(strings.Split(expectedRe, "\n"), td.Re)))
=> feat(Flatten): allow func(T, X...) V|(V, bool) function signatures
